- name: Install dnf-plugins-core
  tags: server,docker,builder,buildx
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - git
    state: latest
    update_cache: true

- name: Install docker daemon
  tags: server,docker,builder,buildx
  ansible.builtin.dnf:
    name: docker
    state: latest

- name: Add user to the docker group
  tags: server,docker,builder,buildx
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: true

- name: Start docker daemon
  tags: server,docker,builder,buildx
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Generate TLS certificates
  tags: server,docker,builder,buildx,ssl,tls
  ansible.builtin.command: SAN="{{ inventory_hostname }} {{ ansible_host }}" docker buildx bake "https://github.com/moby/buildkit.git#master:examples/create-certs"
  args:
    creates: ./.certs

- name: Copy TLS certificates to the ansible controller
  tags: server,docker,builder,buildx
  ansible.builtin.fetch:
    src: "/home/ec2-user/.certs/client/{{ item }}"
    dest: ./.certs/client/
    flat: true
  loop:
    - ca.pem
    - cert.pem
    - key.pem
