- name: Install dnf-plugins-core
  tags: server,docker,builder,buildx
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - git
    state: latest
    update_cache: true

- name: Install docker daemon
  tags: server,docker,builder,buildx
  ansible.builtin.dnf:
    name: docker
    state: latest

- name: Add user to the docker group
  tags: server,docker,builder,buildx
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: true

- name: Start docker daemon
  tags: server,docker,builder,buildx
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Generate TLS certificates
  ansible.builtin.shell:
    cmd: docker buildx bake "https://github.com/moby/buildkit.git#master:examples/create-certs"
  environment:
    SAN: "{{ inventory_hostname }} {{ ansible_host }}"
  args:
    creates: ./.certs
    executable: /bin/bash

- name: Copy TLS certificates to the ansible controller
  tags: server,docker,builder,buildx
  ansible.builtin.fetch:
    src: "/home/ec2-user/.certs/client/{{ item }}"
    dest: ./.certs/client/
    flat: true
  loop:
    - ca.pem
    - cert.pem
    - key.pem

- name: Install qemu emulator binaries
  tags: server,docker,builder,buildx
  community.docker.docker_container:
    name: binfmt
    image: tonistiigi/binfmt:latest
    privileged: true
    auto_remove: true
    command: --install all

- name: Start containerized BuildKit daemon
  tags: server,docker,builder,buildx
  community.docker.docker_container:
    name: buildkitd
    image: moby/buildkit:latest
    privileged: true
    ports:
      - "1537:1537"
    volumes:
      - ./.certs:/etc/buildkit/certs
    command: >
      --addr tcp://0.0.0.0:1537
      --tlscacert /etc/buildkit/certs/daemon/ca.pem
      --tlscert /etc/buildkit/certs/daemon/cert.pem
      --tlskey /etc/buildkit/certs/daemon/key.pem
